language: node_js
node_js:
  - "lts/*"
  - "node"

addons:
  chrome: stable

before_install:
  - npm install -g grunt-cli

install: npm install

script: grunt with_coverage --verbose

after_success: grunt coveralls
